<?php

namespace VPM\TransporteurBundle\Repository;

/**
 * RelaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelaiRepository extends \Doctrine\ORM\EntityRepository
{
}
