<?php

namespace VPM\ProduitBundle\Repository;

/**
 * LogoMarqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogoMarqueRepository extends \Doctrine\ORM\EntityRepository
{
}
