<?php

namespace VPM\CommandeBundle\Repository;

/**
 * EtatPanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatPanierRepository extends \Doctrine\ORM\EntityRepository
{
}
