<?php

namespace VPM\CommandeBundle\Repository;

/**
 * MethodePaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MethodePaiementRepository extends \Doctrine\ORM\EntityRepository
{
}
