<?php

namespace VPM\VehiculeBundle\Repository;

/**
 * CylindreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CylindreRepository extends \Doctrine\ORM\EntityRepository
{
}
