<?php

namespace VPM\UtilisateurBundle\Repository;

/**
 * TypeAdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAdresseRepository extends \Doctrine\ORM\EntityRepository
{
}
