# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:

        # Firewall principal pour le reste de notre site
        main:
            pattern:        ^/
            anonymous:      true
            provider:       fos_userbundle
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                #success_handler: acme_user.form.handler.login_success
                #failure_handler: acme_user.form.handler.login_failure
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                secret:        %secret% # %secret% est un paramètre de parameters.yml

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin$, role: ROLE_ADMIN }
        - { path: ^/panier/livraison, role: ROLE_USER}
        - { path: ^/adresse$, role: ROLE_USER}