admin_produit_index:
    path:     /
    defaults: { _controller: "VPMAdminBundle:Produit:index" }
    methods:  GET

admin_produit_show:
    path:     /{id}/show
    defaults: { _controller: "VPMAdminBundle:Produit:show" }
    methods:  GET

admin_produit_new:
    path:     /new
    defaults: { _controller: "VPMAdminBundle:Produit:new" }
    methods:  [GET, POST]

admin_produit_edit:
    path:     /{id}/edit
    defaults: { _controller: "VPMAdminBundle:Produit:edit" }
    methods:  [GET, POST]

admin_produit_delete:
    path:     /{id}/delete
    defaults: { _controller: "VPMAdminBundle:Produit:delete" }
    methods:  DELETE
